services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_api_with_sqlserver_v2
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80;
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=YoutubeProductDb;User Id=sa;Password=Netcode2024;TrustServerCertificate=true;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Netcode2024"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sqlcmd -Q 'SELECT 1' -S sqlserver -U sa -P Netcode2024"
        ]
      interval: 10s
      retries: 10
networks:
  default:
    name: my_custom_network

volumes:
  sqlserverdata:
